### ISSUE TITLE
Heroku demo is down

### ISSUE THREAD

**Issue by muhammad-saleh** [AMR-KELEG/Franco-Arabic-Transliterator#13]
Could you please fix the demo environment? The Heroku app is down.
Thank you!

**Comment by AMR-KELEG** [comment]
Hi @muhammad-saleh 
Thanks for your interest in the project.
Maintaining the site on heroku proved to be hard. However, I created a new demo on HuggingFace spaces: https://huggingface.co/spaces/AMR-KELEG/Franco-Arabic-Transliterator
It would be great if you could kindly share your feedback, as I am already planning to improve the tool.
