### ISSUE TITLE
Make sure installation works correctly

### ISSUE THREAD

**Issue by AMR-KELEG** [AMR-KELEG/Franco-Arabic-Transliterator#4]
Does `hfst` needs special installation steps?

**Comment by rblcoder** [comment]
Hi @AMR-KELEG , it works here https://www.kaggle.com/rblcoder/hfst-import is there any additional check needed?

**Comment by AMR-KELEG** [comment]
Hi @rblcoder,

I am **really** really glad you have helped me with that :smile: 
Actually, your code is more than enough.
Thanks a lot for your contribution :smile:
(BTW, you could have just used `pip install franco_arabic_transliterator`)

On the other hand, Are you mainly interested in the repository?
Is there something I should focus on finalizing?

**Comment by AMR-KELEG** [comment]
Hi @rblcoder,

I am really really glad you have helped me with that smile
Actually, your code is more than enough.
Thanks a lot for your contribution smile
(BTW, you could have just used pip install franco_arabic_transliterator)

On the other hand, Are you mainly interested in the repository?
Is there something I should focus on finalizing?

**Comment by rblcoder** [comment]
Thank you @AMR-KELEG!
I was searching for issues with label 'help wanted', like this 
http://github-help-wanted.com/?languages=Python&labels=help+wanted&page=1&sort=created&order=desc  and found the issue you had created. Thank you for your reply!

**Comment by AMR-KELEG** [comment]
Hmmm Interesting.
Thanks and have a nice day.
